config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :teachers, only: [:index, :show]
  resources :courses do
    resources :bookings, only: [:new, :create, :show, :destroy] do
          resources :payments, only: :new
    end
  end

   #do resources :bookings....
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:show]
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  # validates :styles, :title, :address, :description, :price, :language, :availability, :date, :start_time, :end_time, presence: true
  # validates :title, length: { minimum: 3 }
  # validates :description, length: { minimum: 15 }
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :first_name, :last_name, presence: true
  # validates :email, presence: true
  has_many :bookings, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_one_attached :profile_avatar
  has_one_attached :card_image

  enum status: { teacher: 0, student: 1 }

  def self.teachers
    User.where(status: 0)
  end

  def self.students
    User.where(status: 1)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  include Pundit
   after_action :verify_authorized, except: [:new, :index, :show], unless: :skip_pundit?
   after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

    private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.create(user_id: current_user.id, course_id: params[:course_id])
    @course = Course.find(params[:course_id])


    session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
          name: @course.title,
          amount: (@course.price * 100).to_i,
          currency: 'eur',
          quantity: 1

        }],
        success_url: booking_url(@booking),
        cancel_url: booking_url(@booking)
      )
      @booking.update(checkout_session_id: session.id)
      redirect_to  new_course_booking_payment_path(@course, @booking)
      authorize @booking
  end

  def show
    @booking = Booking.find(params[:id])

    @markers = [
      {
        lat: @booking.course.latitude,
        lng: @booking.course.longitude
      }]
  end

  def destroy
    set_booking
    @booking.destroy
    redirect_to root_path
  end

private

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  def index
  end


  def show
    @course = Course.find(params[:id])

    @teacher = @course.user


    # @markers = {lat:location.first.coordinates[0], lng:location.first.coordinates[1]}

    @markers = [
      {
        lat: @course.latitude,
        lng: @course.longitude
      }]
    end

   # @user = current_user
   # @teacher.price = @course

  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    # @teachers = User.address_based_teacher_search(params[:query])
  end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new
    @booking = current_user.bookings.where(state: 'pending').find(params[:booking_id])

    course = Course.find(params[:course_id])
    @teacher = course.user
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @teachers = User.teachers
    apply_filters if params[:query]

    @styles = []
    Course.all.each do |course|
      @styles << course.classstyle
    end
    @styles.uniq!

    @addresses = []
    Course.all.each do |course|
      @addresses << course.address
    end
    @addresses.uniq!

    @levels = []
    Course.all.each do |course|
      @levels << course.level
    end
    @levels.uniq!

    @prices = []
    Course.all.each do |course|
      @prices << course.price
    end
    @prices.uniq!
    @prices.sort_by!(&:to_i)

    @ratings = []
    User.teachers.each do |teacher|
      @ratings << teacher.ratings
    end
    @ratings.uniq!
    @ratings.sort_by!(&:to_i)

    @user = policy_scope(User)
  end

  def show
    @teacher = User.teachers.find(params[:id])
    # @booking = Booking.new
    authorize @teacher

    @teacher.courses.each do |course|
      location = Geocoder.search(course.address)
     # course.latitude = location.first.coordinates[0]
     # course.longitude = location.first.coordinates[1]
    end
    # @markers={lat:location.first.coordinates[0], lng:location.first.coordinates[1] }

    @markers = @teacher.courses.geocoded.map do |course|
      {
        lat: course.latitude,
        lng: course.longitude
      }
    end
  end

  def apply_filters
    if params[:query][:address].present?
      @teachers = @teachers.joins(:courses).where("address ILIKE ?", "%#{params[:query][:address]}%")
     end
    if params[:query][:date].present?
      @teachers = @teachers.joins(:courses).where(courses: {date: params[:query][:date]})
    end
    if params[:query][:style].present?
      @teachers = @teachers.joins(:courses).where(courses: {classstyle: params[:query][:style]})
    end
    if params[:query][:level].present?
      @teachers = @teachers.joins(:courses).where(courses: {level: params[:query][:level]})
    end
    if params[:query][:price].present?
      @teachers = @teachers.joins(:courses).where(courses: {price: (0.0..params[:query][:price].to_f)})
    end
     if params[:query][:ratings].present?
      @teachers = @teachers.where(ratings: params[:query][:ratings])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div style="background-color: white;">
<div class="container-booking-confirmation ">
  <div class="card-body">
  <h2 id="greeting-1" style="display: flex; flex-direction: row; justify-content: left; align-items: left; margin-top: 14px;" > Hi <%= current_user.first_name%>,</h2>
  <h5 id="greeting-2"style="display: flex; flex-direction: row; justify-content: left; align-items: left; margin-top: 14px;" > Thank you for booking your class with us 🌞 </h5>
  <h5 id="greeting-2"> See you on the mat! </h6>
</div>
<div class="index-cards-booking">
  <% search_items = ["yoga", "pilates", "yogis", "yogi", "yoga teacher", "yoga trainer", "yoga class"] %>
  <div class="card-teacher">
  <div class="img-booking"></div>

    <div class="card-teacher-infos">
      <div class="headline-area">
        <h2> <%= @booking.course.classstyle %> Yoga </h2>
        <div class="text-muted" style="font-size: 12px;">
        </div>
      </div>
        <hr>
        <p>🗓 Date: <%= @booking.course.date%></p>
        <p>⏱ Duration: <%= @booking.course.start_time.strftime("%H:%M")%> - <%= @booking.course.end_time.strftime("%H:%M") %> </p>
        <p>📍 <%= @booking.course.address %></p>
    </div>
  </div>


  <div id="map"
          style="width: 100%; height: 240px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>

<div>
       <%= link_to "Explore more teachers & classes", root_path, class:"btn-style-confirmation" %>
  </div>
    </div>

    <%#= link_to "Explore more", root_path, class:"btn-classes" %>

app/views/courses/index.html.erb
    <div class="paymentlogo"></div>

app/views/courses/show.html.erb
<div class="background">
<div class=".go-back-button">
 <%= link_to "<", teachers_path, class:"go-back-button" %>
  </div>
    <div class="card-white" id="course-introduction">
      <h2><strong> <%= @course.classstyle %> Yoga</strong></h2>
      <p>🗓 <%= @course.date.strftime("%B %d, %Y") %>
      <p>⏱ <%= @course.start_time.strftime("%H:%M") %> - <%= @course.end_time.strftime("%H:%M") %> </p>
      <p> <% 5.times do %>
        <i class="fas fa-star"></i>
        <% end %> <reviews> | <%= rand(500..999) %> reviews</reviews></p>
    </div>
    </div>

    <div class="background-cards">
    <div class="card-white" id="course-teacher">
      <%= cl_image_tag @teacher.profile_avatar.key, height: 100, width: 100, class: "img-circle" %>
      <div>
      <p class="teacher"><strong><%= @teacher.first_name %> <%= @teacher.last_name %></strong></p>
       <% if @teacher.certification %>
       <p class="certification"> Certified teacher <i class="far fa-file-pdf"></i></p>
      <% else %>
      <% end %>
     </div>
    </div>

    <div class="card-white" id="course-description">
      <p><%= @course.description %></p>
      <p><i class="far fa-credit-card"></i><strong><%= @course.price %> <i class="fas fa-euro-sign"></i> / class </strong></p>
      <div id="map"
          style="width: 100%; height: 240px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <br />
      <p>📍 <%= @course.address %></p>
      </div>

    <div class="card-white" id="course-booking">
    <p>3 out of 20 spots available</p>
    <%= form_tag course_bookings_path(@course) do %>
    <%= hidden_field_tag 'course_id', @course.id %>
    <%= submit_tag 'Purchase', class: 'btn-style' %>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetTheYogis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- app/views/layouts/application.html.erb -->
    <%= favicon_link_tag 'yogis.png' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://unpkg.com/@tabler/icons@latest/iconfont/tabler-icons.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

      <% unless action_name == 'show' || 'index' %>
        <!-- <%= render 'shared/navbar' %> -->
      <% end %>

      <%= yield %>
      <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>
<style>
  body{background-color: #003d39;}
</style>
<div class="home-content">
  <div class="logo-home">
  </div>
  <h1>Discover, Connect & Book Yoga Teachers</h1>
  <%= simple_form_for :query, url: teachers_path, method: "GET", html: { class: 'search-form' } do |f| %>
  <%= f.input :address, label: false, placeholder: "Where do you want to practise?", input_html: { class: "search-input" } %>
  <%= f.button :submit, "Go", class: "search-btn" %>
  <% end %>
  <div class="cards">
    <div class="step-card">
      <div class="heading-area">
        <h1>1</h1>
        <h2>Location</h2>
      </div>
        <div class="grey-area">
          <p>Insert your location and see which yoga teachers are available</p>
        </div>
    </div>
      <div class="step-card">
        <div class="heading-area">
          <h1>2</h1>
          <h2>Find a teacher</h2>
        </div>
        <div class="grey-area" id="right-side">
          <p>Find the right teacher based on your prefered style and budget</p>
        </div>
      </div>
      <div class="step-card">
        <div class="heading-area">
          <h1>3</h1>
          <h2>Pick a Class</h2>
        </div>
        <div class="grey-area">
          <p>View information about a class and decide if it's right for you</p>
        </div>
      </div>
      <div class="step-card">
        <div class="heading-area">
          <h1>4</h1>
          <h2>Book and Pay</h2>
        </div>
        <div class="grey-area" id="right-side">
          <p>Just put your payment details in, book your class and bring your mat!</p>
        </div>
      </div>
  </div>
    <%= simple_form_for :query, url: teachers_path, method: "GET", html: { class: 'get-started-form' } do |f| %>
      <%= f.button :submit, "Get started", class: "get-started-btn" %>
    <% end %>
</div>
<div class="banner"></div>
<div class="second_banner"></div>

app/views/payments/new.html.erb
<div style="background-color: white;">

<div class="container-test">
  <div class="row justify-content">
    <div class="col-12 mt-3">
      <div class="image-booking">
        <%= link_to "<", root_path, class:"transparent-btn"%>
        <h1> Booking Summary </h1>
      </div>
      <div class= title-text>
        <%= @booking.course.classstyle %> Yoga with <%= @teacher.first_name %> <%= @teacher.last_name %>
     </div>
    <div class="container-payments-info">
      <div class="booking-details">
        <p> <%= @booking.course.date.strftime("%B %d, %Y") %>
          <p><%= @booking.course.start_time.strftime("%H:%M") %> - <%= @booking.course.end_time.strftime("%H:%M") %> </p>
          <hr>
          <p> <%= @booking.course.address %>
      <div class="icons-payment">
        <p> ⏱ </p>
        <h1>📍</h1>
        <hr>
      </div>
      <div class="total">
        Total
      </div>
      <div class="total-euro">
        <%= @booking.course.price %> <i class="fas fa-euro-sign"></i>
      </div>
    </div>
  </div>
  <button id="pay" class="payment-button"> Proceed to payment </button>
    <script src="https://js.stripe.com/v3/"></script>
    <script>
      const paymentButton = document.getElementById('pay');
      paymentButton.addEventListener('click', () => {
        const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
        stripe.redirectToCheckout({
          sessionId: '<%= @booking.checkout_session_id%>'
        });
      });
    </script>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="color: white;">
  <%# <%= link_to "#", class: "navbar-brand" do %>
    <%# <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <%# <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <!-- <%= link_to "Messages", "#", class: "nav-link" %> -->
        </li>
        <li class="nav-item dropdown">

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/teachers/index.html.erb
<div style="background-color: white;">

  <div class="index-header">
  <%= link_to "<", root_path, class:"transparent-btn"%>
  </div>

<div id="search-area">
  <h2> Discover Yoga Teachers</h2>
  <div class="index-form">
    <%= simple_form_for :query, url: teachers_path, method: "GET", html: { autocomplete: 'off' } do |f| %>
    <div class="filters">
      <%= f.input :address, label: false, placeholder: "Location", input_html: { class: "index-input" } %>
      <%= f.input :date, as: :string, required: false, label: false, placeholder: "Date", prompt: "Date", input_html: {class: "datepicker index-input"}%>
      <%= f.input :style, collection: @styles, label: false, prompt: "Style", input_html: { class: "index-input" } %>
      <%= f.input :price, collection: @prices, label: false, prompt: "Price", input_html: { class: "index-input-2" } %>
      <%= f.input :level, collection: @levels, label: false, prompt: "Level", input_html: { class: "index-input-2" } %>
      <%= f.input :ratings, collection: @ratings, label: false, prompt: "Rating", input_html: { class: "index-input-2" } %>
    </div>
      <%= f.button :submit, "Apply filters", class: "index-btn" %>
      <% end %>
  </div>
</div>

<div class="index-cards">

  <% search_items = ["yoga", "pilates", "yogis", "yogi", "yoga teacher", "yoga trainer", "yoga class"] %>

  <% @teachers.each do |teacher| %>

  <%= link_to teacher_path(teacher)  do %>

  <div class="card-teacher">

    <%= cl_image_tag teacher.card_image.key%>
    <div class="card-teacher-infos">

      <div>
        <% if teacher.certification == true %>
          <p>Certified | <%= teacher.certificationhours %>h Yoga Alliance </p>
          <% else %>
          <p> Community Teacher </p>
          <% end %>
      </div>

      <div class="headline-area">
        <h2><%= teacher.first_name %> <%= teacher.last_name %></h2>
        <div style="font-size: 10px; color: #666963; align-self: center;">
          <% teacher.ratings.times do %>
            <i class="fas fa-heart"></i>
          <% end %>
        </div>
      </div>
<hr>


      <div style="display: flex;">

        <div style="flex-grow: 3;">
          <p><%= teacher.style %> <vertical-bar>&#124;&#124;&#124;&#124;&#124;</vertical-bar> </p>
          <p><%= teacher.courses.pluck(:level).uniq.join(" | ")%></p>

          <div style="display:flex; justify-content: flex-start; margin-top: 20px;">
            <p style="margin-right: 10px;"><i class="fas fa-map-marker-alt" style="font-size: 20px;"></i> Berlin</p>
            <p><i class="fas fa-euro-sign" style="font-size: 20px;"></i> from <%= "#{[15.99, 18.50,12.99,13.99,14.75].sample}" %></p>
          </div>

        </div>

        <div style="display: flex; justify-content: top; flex-end; flex-grow:1;">
          <p style="font-size: 35px; color: #00635D;"><i class="fas fa-chevron-right"></i></p>
        </div>

      </div>

    </div>
  </div>
  <% end %>
  <% end %>
</div>

<!-- <p><i class="fas fa-euro-sign" style="font-size: 20px;"></i> <%= "#{[15.99, 18.50,12.99,13.99,14.75].sample}" %>+</p>
 -->
<div class="index-footer">
  <p style= "text-align: center;">Create your account today, it is easy and quick!</p>
  <a class="aquagreen-btn-footer" href="#" role="button">Create an account</a>
</div>
</div>

app/views/teachers/show.html.erb
<%= link_to teachers_path, class:"go-back-button" do %>
  <i class="ti ti-chevron-left"></i>
<% end %>

<iframe width="100%" height="300" src="https://www.youtube.com/embed/SZCxKjgReQ4?modestbranding=0&showinfo=0&fs=0" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; picture-in-picture"></iframe>

<div class="container-teachers-info">
  <div class="teachers-title">
    <h2><%= @teacher.first_name %> <%= @teacher.last_name %></h2>
    <i class="far fa-heart" id="heart-avatar"></i>
  </div>
  <div>
    <% if @teacher.certification == true %>
    <p> Certified Teacher | <%= @teacher.certificationhours %>h Yoga Alliance </p>
    <% else %>
    <p> Community Teacher </p>
    <% end %>
    <hr>
  </div>
  <div class="yoga-teachers-styles">
    <p>Ashtanga <vertical-bar>&#124;&#124;&#124;&#124;&#124;</vertical-bar> Vinyasa <vertical-bar>&#124;&#124;&#124;</vertical-bar>&#124;&#124; Yin <vertical-bar>&#124;&#124;</vertical-bar>&#124;&#124;&#124;</p>
  </div>
  <hr>

  <div class="about-me">
    <h5><strong>About me</strong></h5>
    <p><%= @teacher.about_me %></p>
  </div>
  <hr>

  <div class="reviews">
    <% 5.times do %>
    <i class="fas fa-star"></i>
    <% end %> <reviews><%= rand(500..999) %> reviews</reviews>
  <hr>
  </div>

  <div>
    <h5><strong>Next classes</strong></h5>
  </div>

  <div class="teacher-cards">
    <% levels = ["easy level", "moderate level", "advanced level", "all levels"] %>
    <% @teacher.courses.each do |course| %>
    <div class="card-classes">
      <div class="card-horizontal" style="display: flex; flex: 1 1 auto; height: 100%;">
        <div style="display: flex; justify-content: center; align-items: center;">
          <%= cl_image_tag course.photo.key, height: 100, width: 170, class:"card-img"%>
        </div>
        <div class="card-body" style="padding: 1.25rem 0.75rem">
          <div class="course-name">
            <h5 class="card-title"><strong><%= course.classstyle %> Yoga</strong></h5>
            <i class="far fa-heart" id="heart-card" style="font-size: 0.9em;"></i>
          </div>
          <p class="card-text"><strong><%= course.price %> </strong><small><i class="fas fa-euro-sign"></i></small> / class</p>
          <%= link_to "See more", course_path(course), class:"btn-classes" %>
        </div>
      </div>
    </div>
    <hr>
    <% end %>
  </div>

  <div id="map"
    style="width: 100%; height: 500px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="jumbotron">
    <a href="#" role="button"><i class="fas fa-th-large" id="heart-footer"></i></a>
    <a href="#" role="button"><i class="far fa-heart" id="heart-footer"></i></a>
    <a href="#" role="button"><i class="far fa-user" id="heart-footer"></i></a>
  </div>
</div>